# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_userauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(help_text='微信用户绑定和CC视频统计', max_length=64, unique=True),
        ),
    ]
