# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20171125_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='可提现和使用余额'),
        ),
    ]
