# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponrecord',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.Account', verbose_name='拥有者'),
            preserve_default=False,
        ),
    ]
