# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_taggeditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeditem',
            name='content_type',
        ),
    ]
