# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_taggeditem_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeditem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
