# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171123_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeditem',
            name='password',
        ),
    ]
