# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userauthtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
        migrations.DeleteModel(
            name='UserAuthToken',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
