# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_coupon_course_degreecourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='DegreeCourse',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
