"""
Django settings for luffycity project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ciwel&67m-5+2mbu-e+v3r)^wgvshnl(mm&**7)j4uv94)ap(*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api.apps.ApiConfig',
    'repository',
    'app01',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middlewares.cors.CorsMiddleware'
]

ROOT_URLCONF = 'luffycity.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'luffycity.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# REST_FRAMEWORK = {
#     "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
#     'DEFAULT_VERSION': 'v1',
#     'ALLOWED_VERSIONS': ['v1', ],
#     'VERSION_PARAM': 'version',
#     "DEFAULT_PERMISSION_CLASSES": [
#         "api.utils.auth.token_permission.LuffyPermission",
#     ],
#     "DEFAULT_AUTHENTICATION_CLASSES": [
#         "api.utils.auth.token_auth.LuffyTokenAuthentication",
#     ]
#
# }

# REST_FRAMEWORK = {
#     'DEFAULT_THROTTLE_CLASSES': [
#         'api.utils.throttles.throttles.LuffyAnonRateThrottle',
#         'api.utils.throttles.throttles.LuffyUserRateThrottle',
#     ],
#     'DEFAULT_THROTTLE_RATES': {
#         'anon': '10/day',
#         'user': '10/day',
#         'luffy_anon': '10/m',
#         'luffy_user': '20/m',
#         'luffy_msg': '10/d',
#     },
# }

# REST_FRAMEWORK = {
#     # 'UNAUTHENTICATED_USER': None,
#     # 'UNAUTHENTICATED_TOKEN': None,
#     # "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
#     # 'DEFAULT_VERSION': 'v1',
#     # 'ALLOWED_VERSIONS': ['v1', 'v2'],
#     # 'VERSION_PARAM': 'version',
#     # "DEFAULT_PERMISSION_CLASSES": [
#     #     "rest_framework.permissions.AllowAny",
#     # ],
#     # 'DEFAULT_THROTTLE_CLASSES': [
#     #     # 'rest_framework.throttling.AnonRateThrottle'
#     #     # 'rest_framework.throttling.UserRateThrottle'
#     #     # 'api.utils.throttles.throttles.LuffyAnonRateThrottle',
#     #     # 'api.utils.throttles.throttles.LuffyUserRateThrottle',
#     #     # 'api.utils.throttles.throttles.LuffyMessageRateThrottle',
#     # ],
#     # 'DEFAULT_THROTTLE_RATES': {
#     #     # 'anon': '10/day',
#     #     # 'user': '10/day',
#     #     # 'luffy_anon': '10/m',
#     #     # 'luffy_user': '20/m',
#     #     # 'luffy_msg': '10/d',
#     # },
#     # 'DEFAULT_PARSER_CLASSES': (
#     #     'rest_framework.parsers.JSONParser',
#     # ),
#     # "DEFAULT_RENDERER_CLASSES": (
#     #     'rest_framework.renderers.JSONRenderer',
#     # ),
#     # 'UNICODE_JSON': True,
#     # 'URL_FORMAT_OVERRIDE': True,
# }


CORS_API = "http://localhost:8080"

# ######### 缓存 ############
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # "LOCATION": "redis://192.168.0.100:6379",
        # "LOCATION": "redis://192.168.0.94:6379",
        "LOCATION": "redis://192.168.16.27:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "woshiniba",
            "CONNECTION_POOL_KWARGS": {"max_connections": 5},
        }
    }
}

REDIS_SHOPPING_CAR_KEY = "luffy_shopping_car"
REDIS_PAYMENT_KEY = "luffy_payment"

# ########## REST_FRAMEWORK########
REST_FRAMEWORK = {
    'UNAUTHENTICATED_USER': None,
    'UNAUTHENTICATED_TOKEN': None,
}

# ######### 支付宝支付 ##########
APPID = "2016081500252288"  # 2016082500309412
# 商户私钥路径
MERCHANT_PRIVATE_KEY_PATH = os.path.join(BASE_DIR, "keys", "app_private_2048.txt")
# merchant_private_key_path = os.path.join(BASE_DIR, "keys", "pri")

# 支付宝公钥路径
ALIPAY_PUBLIC_KEY_PATH = os.path.join(BASE_DIR, "keys", "alipay_public_2048.txt")
# alipay_public_key_path = os.path.join(BASE_DIR, "keys", "pub")

# 服务器异步通知页面路径 需http: // 格式的完整路径，不能加?id = 123 这类自定义参数，必须外网可以正常访问
# 发post请求
NOTIFY_URL = "http://47.94.172.250:8804/api/v1/alipay/"

# 页面跳转同步通知页面路径 需http: // 格式的完整路径，不能加?id = 123 这类自定义参数，必须外网可以正常访问
# 发get请求
RETURN_URL = "http://47.94.172.250:8804/api/v1/alipay/"

# 签名方式(当前只支持RSA和RSA2)
SIGN_TYPE = "RSA2"

# 字符编码格式
CHARSET = "utf-8"

# 支付宝网关(如果是线上环境的话, dev 这三个字去掉即可)
GATEWAY_URL_DEV = "https://openapi.alipaydev.com/gateway.do"
GATEWAY_URL = "https://openapi.alipay.com/gateway.do"

# 异步通知参数DOC(支付宝会主动发起POST请求)
# notify_doc = "https://docs.open.alipay.com/270/105902/"
